dist: xenial
sudo: required
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
script:
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j$(nproc)