dist: bionic
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblua5.3-dev
      - liblua5.3
      - openssl
      - gcc-10
      - g++-10
      - cmake

matrix:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64
    - os: linux
      arch: ppc64le
    - os: linux
      arch: s390x

script:
  - cd cmake-build-release
  - export CC=$(which gcc-10)
  - export CXX=$(which g++-10)
  - cmake -DCMAKE_BUILD_TYPE=Release .. &&
    make -j$(nproc) &&
    make test SHOW_INTERACTIVE_LOG=1