dist: bionic
sudo: required
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblua5.3-dev
      - liblua5.3
      - openssl
      - gcc-10
      - g++-10
      - cmake
script:
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j$(nproc)